package: adispatch
platform:
  - linux-64
  - linux-32
  - osx-64
  - win-64
engine:
  - python=3.3
  - python=3.4
  - python=3.6
  - python=3.7
script:
  - touch build.sh
  - conda build .
build_targets:
  files: conda
  channels: main
