language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install coverage

script:
  - nosetests --with-doctest

deploy:
  provider: pypi
  user: waipu
  password:
    secure: "AkcoiJJZPoIOYFsAssTIe01+INrcWLNPibRgo5PPHfQ87iBJJehEWTlX/CP4m1Bv+kwstnBIGVe75Tk0okJklLpCQZe6TrvhtM54E///n1y6+jtlg1wke3GMKBYqpRLUDnHllVYAC6+YsREIcxClRZtjft9Qu+9wuOmPCB7f53U="
  on:
    tags: true

notifications:
  email: false
